/**
 * @fitmate/pixel-ui — Tailwind CSS preset.
 * Usage in tailwind.config.js:
 *   import pixelPreset from "@fitmate/pixel-ui/tailwind-preset";
 *   export default { presets: [pixelPreset], content: [...] };
 */
export default {
  theme: {
    extend: {
      colors: {
        /* pixel palette */
        "pixel-black": "#101010",
        "pixel-white": "#F8F8F8",
        "pixel-gray": "#6B6B6B",
        "pixel-blue": "#3A5BA0",
        "pixel-green": "#2D7D46",
        "pixel-yellow": "#D4A533",
        "pixel-red": "#A83232",
        "pixel-page": "#E8E8E8",
        /* semantic tokens (resolve to pixel palette via tokens.css) */
        "surface": "var(--color-surface)",
        "surface-dim": "var(--color-surface-dim)",
        "surface-bright": "var(--color-surface-bright)",
        "surface-container-lowest": "var(--color-surface-container-lowest)",
        "surface-container-low": "var(--color-surface-container-low)",
        "surface-container": "var(--color-surface-container)",
        "surface-container-high": "var(--color-surface-container-high)",
        "surface-container-highest": "var(--color-surface-container-highest)",
        "on-surface": "var(--color-on-surface)",
        "on-surface-variant": "var(--color-on-surface-variant)",
        "inverse-surface": "var(--color-inverse-surface)",
        "inverse-on-surface": "var(--color-inverse-on-surface)",
        "outline": "var(--color-outline)",
        "outline-variant": "var(--color-outline-variant)",
        "surface-tint": "var(--color-surface-tint)",
        "primary": "var(--color-primary)",
        "on-primary": "var(--color-on-primary)",
        "primary-container": "var(--color-primary-container)",
        "on-primary-container": "var(--color-on-primary-container)",
        "inverse-primary": "var(--color-inverse-primary)",
        "secondary": "var(--color-secondary)",
        "on-secondary": "var(--color-on-secondary)",
        "secondary-container": "var(--color-secondary-container)",
        "on-secondary-container": "var(--color-on-secondary-container)",
        "tertiary": "var(--color-tertiary)",
        "on-tertiary": "var(--color-on-tertiary)",
        "tertiary-container": "var(--color-tertiary-container)",
        "on-tertiary-container": "var(--color-on-tertiary-container)",
        "error": "var(--color-error)",
        "on-error": "var(--color-on-error)",
        "error-container": "var(--color-error-container)",
        "on-error-container": "var(--color-on-error-container)",
        "primary-fixed": "var(--color-primary-fixed)",
        "primary-fixed-dim": "var(--color-primary-fixed-dim)",
        "on-primary-fixed": "var(--color-on-primary-fixed)",
        "on-primary-fixed-variant": "var(--color-on-primary-fixed-variant)",
        "secondary-fixed": "var(--color-secondary-fixed)",
        "secondary-fixed-dim": "var(--color-secondary-fixed-dim)",
        "on-secondary-fixed": "var(--color-on-secondary-fixed)",
        "on-secondary-fixed-variant": "var(--color-on-secondary-fixed-variant)",
        "tertiary-fixed": "var(--color-tertiary-fixed)",
        "tertiary-fixed-dim": "var(--color-tertiary-fixed-dim)",
        "on-tertiary-fixed": "var(--color-on-tertiary-fixed)",
        "on-tertiary-fixed-variant": "var(--color-on-tertiary-fixed-variant)",
        "background": "var(--color-background)",
        "on-background": "var(--color-on-background)",
        "surface-variant": "var(--color-surface-variant)",
      },
      /* pixel style: hard edges only — every radius collapses to 0 */
      borderRadius: {
        none: "0",
        DEFAULT: "0",
        sm: "0",
        md: "0",
        lg: "0",
        xl: "0",
        "2xl": "0",
        "3xl": "0",
        full: "0",
      },
      /* hard offset shadows, never blurred */
      boxShadow: {
        "pixel-sm": "2px 2px 0px 0px #101010",
        "pixel-md": "3px 3px 0px 0px #101010",
        "pixel": "4px 4px 0px 0px #101010",
        "pixel-lg": "6px 6px 0px 0px #101010",
        "pixel-xl": "8px 8px 0px 0px #101010",
        "pixel-inset": "inset 2px 2px 0px 0px #101010",
        "pixel-disabled": "2px 2px 0px 0px #666666",
        "pixel-white": "4px 4px 0px 0px #F8F8F8",
        "pixel-white-sm": "2px 2px 0px 0px #F8F8F8",
        "pixel-gray": "4px 4px 0px 0px #6B6B6B",
        "pixel-gray-sm": "2px 2px 0px 0px #6B6B6B",
      },
      borderWidth: {
        3: "3px",
        5: "5px",
        6: "6px",
      },
      spacing: {
        xs: "4px",
        sm: "8px",
        md: "16px",
        lg: "32px",
        xl: "64px",
        unit: "4px",
        gutter: "16px",
        margin: "24px",
      },
      fontFamily: {
        pixel: ["VT323", "ZCOOL KuaiLe", "ui-monospace", "SFMono-Regular", "Menlo", "Monaco", "Consolas", "monospace"],
      },
      keyframes: {
        "bounce-pixel": {
          "0%, 100%": { transform: "translateY(0)" },
          "50%": { transform: "translateY(-8px)" },
        },
        "float": {
          "0%, 100%": { transform: "translateY(0)" },
          "50%": { transform: "translateY(-4px)" },
        },
        "shake": {
          "0%, 100%": { transform: "translateX(0)" },
          "25%": { transform: "translateX(-2px)" },
          "75%": { transform: "translateX(2px)" },
        },
        "typewriter": {
          "0%, 100%": { opacity: "1" },
          "50%": { opacity: "0" },
        },
        "blink": {
          "0%, 100%": { opacity: "1" },
          "50%": { opacity: "0.5" },
        },
      },
      animation: {
        "bounce-pixel": "bounce-pixel 1s ease-in-out infinite",
        "float": "float 3s ease-in-out infinite",
        "shake": "shake 0.3s ease-in-out infinite",
        "typewriter": "typewriter 0.5s steps(1) infinite",
        "blink": "blink 1.2s ease-in-out infinite",
      },
    },
  },
};
